# Generated by Django 2.2.4 on 2019-12-07 21:18

from django.db import migrations, models
import sell.models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='salsa',
        ),
        migrations.AddField(
            model_name='player',
            name='player_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='address',
            field=models.CharField(default=sell.models.get_address, max_length=100),
        ),
    ]
